# Generated by Django 2.1.dev20180406150551 on 2018-06-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='d',
            field=models.IntegerField(verbose_name='Demanda Total'),
        ),
    ]
