# Generated by Django 2.1.dev20180406150551 on 2018-04-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo1',
            name='t',
        ),
    ]
