# Generated by Django 2.1.dev20180406150551 on 2018-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0002_remove_modelo1_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo1',
            name='y',
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='d',
            field=models.IntegerField(verbose_name='Tasa de Demanda'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='h',
            field=models.IntegerField(verbose_name='Costo de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='k',
            field=models.IntegerField(verbose_name='Costo de Preparación de Pedido'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='stock',
            field=models.IntegerField(verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='tiempo',
            field=models.IntegerField(default=1),
        ),
    ]
