# Generated by Django 2.1.dev20180406150551 on 2018-05-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0003_auto_20180527_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo1',
            name='stock',
        ),
    ]
