# Generated by Django 2.1.dev20180406150551 on 2018-07-02 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0003_auto_20180630_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo1',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='modelo1',
            name='b',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Costo Unitario de Producto'),
        ),
        migrations.AddField(
            model_name='modelo1',
            name='unidad',
            field=models.CharField(choices=[('DIAS', 'dias'), ('MES', 'mes'), ('AÑO', 'año')], default='DIAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='d',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Demanda Total'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='h',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Costo Unitario de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='k',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Costo de Preparación de Pedido'),
        ),
    ]
