# Generated by Django 2.1.dev20180406150551 on 2018-07-02 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0004_auto_20180702_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='b',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario de Producto'),
        ),
    ]
