# Generated by Django 2.1.dev20180406150551 on 2018-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0004_remove_modelo1_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='h',
            field=models.FloatField(verbose_name='Costo de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='k',
            field=models.FloatField(verbose_name='Costo de Preparación de Pedido'),
        ),
        migrations.AlterField(
            model_name='modelo1',
            name='tiempo',
            field=models.FloatField(default=1),
        ),
    ]
