# Generated by Django 2.1.dev20180406150551 on 2018-07-02 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0005_auto_20180702_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='h',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario de Almacenamiento'),
        ),
    ]
